# Generated by Django 4.2.3 on 2023-07-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goats_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='seller_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads_as_seller', to='goats_app.user'),
        ),
    ]
